server:
  port: 8181

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/routes
  zipkin:
    baseUrl: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/

management:
  endpoint:
    health:
      show-details: always

# logging
logging:
  level:
    com:
      netflix: OFF