server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/users
  zipkin:
    baseUrl: http://tracingservice:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://registryservice:8765/eureka/