server:
  port: 8181

spring:
  application:
    name: climbingroutesservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/

management:
  endpoint:
    health:
      show-details: always