server:
  port: 8765

spring:
  zipkin:
    baseUrl: http://localhost:9411/

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# logging
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
