server:
  port: 8080

spring:
  application:
    name: usersservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/users

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/

management:
  endpoint:
    health:
      show-details: always