version: '3.7'

services:

  mongo:
    restart: always
    image: mongo:4.0.10
    container_name: "mongodb"
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=adminadmin
      # - MONGO_INITDB_DATABASE=users
    #volumes:
    #  - ./data/db:/var/micro-data/mongodb/data/db
    ports:
      - 27017-27019:27017-27019
    #command: mongod --smallfiles --logpath=/dev/null # --quiet
  mongoexpress:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: adminadmin
  configservice:
    build:
      context: ./config-service
    image: routes-ticker/config-service
    restart: always
    ports:
      - 8888:8888
  usersservice:
    build:
      context: ./users-service
    image: routes-ticker/users-service
    restart: always
    depends_on:
      - mongo
      - configservice
    ports:
      - 8080:8080
  registryservice:
    build:
      context: ./registry-service
    image: routes-ticker/registry-service
    restart: always
    depends_on:
      - configservice
    ports:
      - 8765:8765
  climbingroutesservice:
    build:
      context: ./climbing-routes-service
    image: routes-ticker/climbing-routes-service
    restart: always
    depends_on:
      - configservice
      - mongo
    ports:
      - 8181:8181
  gatewayservice:
    build:
      context: ./gateway-service
    image: routes-ticker/gateway-service
    restart: always
    depends_on:
      - configservice
    ports:
      - 9999:9999
