version: '3.7'

services:

  mongo:
    restart: always
    image: mongo:4.0.10
    container_name: "mongodb"
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=adminadmin
      # - MONGO_INITDB_DATABASE=users
    #volumes:
    #  - ./data/db:/var/micro-data/mongodb/data/db
    ports:
      - 27017-27019:27017-27019
    #command: mongod --smallfiles --logpath=/dev/null # --quiet
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: adminadmin
  users-service:
    build:
      context: ./users-service
    image: routes-ticker/users-service
    restart: always
    depends_on:
      - mongo
    ports:
      - 8080:8080
