server:
  port: 8888

spring:
  config:
    name: configservice
  application:
    name: configservice
  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
